server:
  port: 8081
mariosan:
  client:
    address:
      url: http://localhost:8082/addresses
spring:
  data:
    mongodb:
      hsot: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal